import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { portfolioService } from '../services/portfolioService'
import type { Portfolio } from '../types/portfolio'

const asText = (item: unknown): string => {
  if (typeof item === 'string') return item
  if (item && typeof item === 'object') {
    const record = item as Record<string, unknown>
    return [record.title, record.company, record.role, record.description]
      .filter((part): part is string => typeof part === 'string' && Boolean(part))
      .join(' — ') || JSON.stringify(item)
  }
  return item == null ? '' : String(item)
}
const list = (value: string[] | null) => Array.isArray(value) ? value.map(asText).filter(Boolean) : []
const initials = (value: string | null) => (value || 'Portfolio').split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase()
const rules: Array<[string, string[]]> = [['Programming', ['java', 'python', 'c', 'c++', 'c#']], ['Web', ['html', 'css', 'javascript', 'typescript', 'react', 'angular', 'vue']], ['Database', ['sql', 'mysql', 'postgresql', 'mongodb', 'dbms']], ['Tools', ['git', 'github', 'docker', 'google colab', 'postman']]]
const categorize = (skills: string[]) => { const groups = rules.map(([name]) => [name, [] as string[]] as [string, string[]]); const other: string[] = []; skills.forEach((skill) => { const lowered = skill.toLowerCase(); const group = groups.find(([name]) => rules.find(([rule]) => rule === name)?.[1].some((term) => lowered === term || lowered.includes(term))); (group ? group[1] : other).push(skill) }); return [...groups.filter(([, values]) => values.length), ...(other.length ? [['Additional skills', other] as [string, string[]]] : [])] }
const projectCards = (projects: string[]) => { const cards: Array<{ title: string; description: string }> = []; for (let i = 0; i < projects.length; i += 1) { const title = projects[i]; const next = projects[i + 1]; if (next && (title.includes('|') || title.length < 80)) { cards.push({ title, description: next }); i += 1 } else { cards.push({ title, description: '' }) } } return cards }

export default function PublicPortfolio() {
  const { slug } = useParams()
  const [portfolio, setPortfolio] = useState<Portfolio | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [menuOpen, setMenuOpen] = useState(false)
  useEffect(() => { const timer = window.setTimeout(() => { if (!slug) { setError('This public portfolio is unavailable.'); return } void portfolioService.getPublic(slug).then(setPortfolio).catch(() => setError('This public portfolio is unavailable.')) }, 0); return () => window.clearTimeout(timer) }, [slug])
  const skills = useMemo(() => categorize(list(portfolio?.skills ?? null)), [portfolio])
  if (error) return <main className="public-site"><div className="public-container public-state"><p className="public-kicker">ResumeIQ portfolio</p><h1>Portfolio unavailable</h1><p>The link may be incorrect, unpublished, or no longer active.</p><Link className="public-button" to="/">ResumeIQ</Link></div></main>
  if (!portfolio) return <main className="public-site"><div className="public-container public-state">Loading portfolio…</div></main>
  const projects = projectCards(list(portfolio.projects)); const experience = list(portfolio.experience); const education = list(portfolio.education); const certifications = list(portfolio.certifications); const achievements = list(portfolio.achievements)
  const nav = [['Home', 'home'], ['About', 'about'], ['Skills', 'skills'], ['Experience', 'experience'], ['Projects', 'projects'], ['Education', 'education'], ['Contact', 'contact']]
  return <main className="public-site"><header className="public-nav"><div className="public-container nav-inner"><a className="public-logo" href="#home">{portfolio.headline || 'Portfolio'}</a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle navigation">Menu</button><nav className={menuOpen ? 'public-links public-links-open' : 'public-links'}>{nav.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}</a>)}<a className="nav-cta" href="#contact" onClick={() => setMenuOpen(false)}>Let&apos;s connect</a></nav></div></header>
    <section className="public-hero" id="home"><div className="public-container hero-layout"><div><p className="public-kicker">Hello, I&apos;m</p><h1>{portfolio.headline || 'Professional portfolio'}</h1>{portfolio.bio && <p className="hero-summary">{portfolio.bio}</p>}<div className="hero-actions"><a className="public-button" href="#projects">View my work</a><a className="public-button public-button-secondary" href="#contact">Contact me</a></div><div className="social-links">{portfolio.linkedin_url && <a href={portfolio.linkedin_url} target="_blank" rel="noreferrer">LinkedIn</a>}{portfolio.github_url && <a href={portfolio.github_url} target="_blank" rel="noreferrer">GitHub</a>}{portfolio.email && <a href={`mailto:${portfolio.email}`}>Email</a>}</div></div><div className="hero-art" aria-hidden="true"><div className="avatar-initials">{initials(portfolio.headline)}</div><span className="orb orb-one" /><span className="orb orb-two" /><code>&lt;/&gt;</code></div></div></section>
    <section className="public-section" id="about"><div className="public-container split-layout"><div><p className="public-kicker">About me</p><h2>Building thoughtful digital experiences.</h2><p>{portfolio.bio || 'This professional profile is built from a verified resume.'}</p></div><div className="fact-grid">{portfolio.location && <article><span>Location</span><strong>{portfolio.location}</strong></article>}{education[0] && <article><span>Education</span><strong>{education[0]}</strong></article>}{portfolio.skills?.length ? <article><span>Focus</span><strong>{portfolio.skills.slice(0, 3).join(', ')}</strong></article> : null}</div></div></section>
    {skills.length ? <section className="public-section tint-section" id="skills"><div className="public-container"><p className="public-kicker">Skills</p><h2>Tools and technologies</h2><div className="skill-card-grid">{skills.map(([name, values]) => <article key={name}><h3>{name}</h3><div>{values.map((skill) => <span key={skill}>{skill}</span>)}</div></article>)}</div></div></section> : null}
    <section className="public-section" id="experience"><div className="public-container"><p className="public-kicker">Experience</p><h2>Experience and practical learning</h2>{experience.length ? <ol className="timeline">{experience.map((item) => <li key={item}>{item}</li>)}</ol> : <p className="section-fallback">Currently building practical experience through academic and personal software projects.</p>}</div></section>
    {projects.length ? <section className="public-section tint-section" id="projects"><div className="public-container"><p className="public-kicker">Selected work</p><h2>Projects</h2><div className="project-grid">{projects.map((project) => <article key={`${project.title}-${project.description}`}><div className="project-mark">01</div><h3>{project.title}</h3>{project.description && <p>{project.description}</p>}<span className="project-note">Details from resume</span></article>)}</div></div></section> : null}
    {education.length ? <section className="public-section" id="education"><div className="public-container"><p className="public-kicker">Education</p><h2>Academic foundation</h2><ol className="timeline">{education.map((item) => <li key={item}>{item}</li>)}</ol></div></section> : null}
    {certifications.length ? <section className="public-section tint-section"><div className="public-container"><p className="public-kicker">Training</p><h2>Certifications</h2><div className="simple-list">{certifications.map((item) => <article key={item}>{item}</article>)}</div></div></section> : null}
    {achievements.length ? <section className="public-section"><div className="public-container"><p className="public-kicker">Highlights</p><h2>Achievements</h2><div className="simple-list">{achievements.map((item) => <article key={item}>{item}</article>)}</div></div></section> : null}
    <section className="public-contact" id="contact"><div className="public-container contact-layout"><div><p className="public-kicker">Get in touch</p><h2>Let&apos;s build something meaningful.</h2><p>Available through the contact details below.</p></div><div className="contact-actions">{portfolio.email && <a className="public-button" href={`mailto:${portfolio.email}`}>Email me</a>}{portfolio.phone && <a href={`tel:${portfolio.phone}`}>{portfolio.phone}</a>}{portfolio.location && <span>{portfolio.location}</span>}{portfolio.linkedin_url && <a href={portfolio.linkedin_url} target="_blank" rel="noreferrer">Connect on LinkedIn</a>}{portfolio.github_url && <a href={portfolio.github_url} target="_blank" rel="noreferrer">View GitHub</a>}</div></div></section>
    <footer className="public-footer"><div className="public-container"><span>{portfolio.headline || 'Professional portfolio'}</span><span>© {new Date().getFullYear()} All rights reserved.</span></div></footer></main>
}
